spring.application.name=notification-engine

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY}

ai.model=llama3-8b-8192

spring.data.mongodb.uri=${MONGODB_URI}

spring.main.web-application-type=servlet
server.port=${PORT}